# Generated by Django 3.2.5 on 2021-07-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auctionlisting_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='image_url',
            field=models.URLField(blank=True, default='https://www.atpine.com.au/wp-content/uploads/2016/12/no-image-available.jpg'),
        ),
    ]
