# Generated by Django 3.2.5 on 2021-07-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_auctionlisting_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='image_url',
            field=models.URLField(blank=True, default='https://www.atpine.com.au/wp-content/uploads/2016/12/no-image-available.jpg', null=True),
        ),
    ]
