# Generated by Django 3.2.5 on 2021-07-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_auctionlisting_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='winner',
        ),
    ]
