# Generated by Django 3.2.5 on 2021-07-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_auctionlisting_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='users_in_watchlist',
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='users_in_watchlist', to='auctions.AuctionListing'),
        ),
    ]
