# Generated by Django 3.2.5 on 2021-07-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20210715_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='image_url',
            field=models.URLField(blank=True, default='../static/auctions/no-image-available.jpg', null=True),
        ),
    ]
